# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cc2b78c71fbfde87701312a0551b103f1652040240985d04873a6f558dda178dea5d29067afa58f3103ee4a6711ecdef34412b42cceabb7a5d435d45fa1d928

test:
  secret_key_base: f428812c2c92c240091dc88299623857c5264d637aa3ebf0a91426107bb01de026a0a312ef56898e69fe1674dd7b004a87d72dce8717e79e0e29eace804c287f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
